theme: jekyll-theme-cayman
title: Jianru's homepage
description: Jianru was a PhD student in environmental science. Two years ago Jianru realized that she greatly enjoys doing data analysis, and now she is pursuing her master degree in statistics.

# for local test, change this to
# current_base: http://127.0.0.1:4000/
current_base: https://jianru-shi.github.io
