theme: Cayman theme
title: Jianru's Homepage
description: "Facts are stubborn things, but statistics are pliable."  – Mark Twain 

# for local test, change this to
# current_base: http://127.0.0.1:4000/
current_base: https://jianru-shi.github.io
gems:
  - jemoji
