theme: jekyll-theme-cayman
title: Jianru's Homepage
description: I was a PhD student in environmental science. Two years ago I realized that I greatly enjoys doing data analysis. Now I just earned my master degree in statistics and I am actively seeking a job.

# for local test, change this to
# current_base: http://127.0.0.1:4000/
current_base: https://jianru-shi.github.io
gems:
  - jemoji
