theme: jekyll-theme-cayman
title: Jianru's homepage
description: Jianru was a PhD student in environmental science. Two years ago Jianru realized that she greatly enjoys doing data analysis, and now she is pursuing on her master degree in statistics.
